export const WAT_OFFSET_MS = 60 * 60 * 1000;          // UTC+1 in ms
export const PLATFORM_FEE_RATE = 0.025;               // 2.5%
export const LISTING_CAP_PER_DAY = 10;                // v1 cap — see PRD F2
export const ORDER_CONFIRM_WINDOW_MS = 60 * 60 * 1000; // 60 minutes
export const ORDER_CONFIRM_WARNING_MS = 50 * 60 * 1000; // T+50 minutes
export const ESCROW_BUYER_GHOST_MS = 48 * 60 * 60 * 1000; // 48h auto-fulfil
export const ESCROW_RELEASE_DELAY_MS = 24 * 60 * 60 * 1000; // 24h after fulfil
export const COLD_START_LISTING_CAP = 3;              // new vendor: 3 in first 24h
export const OTP_MAX_ATTEMPTS_PER_HOUR = 3;
export const RESPONSE_RATE_MIN_INQUIRIES = 3;         // min inquiries for badge
export const RESPONSE_RATE_THRESHOLD = 0.80;          // 80% for Fast Responder
export const FEED_CACHE_MAX_LISTINGS = 50;            // per category in AsyncStorage
export const FEED_CACHE_STALE_MS = 30 * 60 * 1000;   // 30 minutes
export const MAX_PHOTOS_PER_LISTING = 2;
export const MAX_LISTING_CATEGORIES = 3;
export const IMAGE_MAX_DIMENSION_PX = 800;
export const IMAGE_QUALITY = 0.8;
export const PRESIGNED_URL_EXPIRY_SECONDS = 300;      // 5 minutes
export const TOKEN_ACCESS_EXPIRY = '24h';
export const TOKEN_REFRESH_EXPIRY = '30d';
